In [2]:
import numpy as np

a = np.array([1,2,4,5,6,7,8,9])

print(a)

print(a.shape)

[1 2 4 5 6 7 8 9]
(8,)


In [3]:
b = np.arange(5)
print(b)

[0 1 2 3 4]


In [5]:
np1 = np.arange(0,10,2)
print(np1)

[0 2 4 6 8]


In [9]:
zeros = np.zeros((5,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
full = np.full((3,3),5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [13]:
list = [2,35,0,29]
nparray = np.array(list)
print(nparray)
nparray[2] = 10
print(nparray)


[ 2 35  0 29]
[ 2 35 10 29]
