In [13]:
import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9])

print(np1[1:5])
print(np1[7:])
print(np1[:8])
print(np1[-4:-1])
print(np1[-1:])
print(np1[2:7:2])
print(np1[::3])

[2 3 4 5]
[8 9]
[1 2 3 4 5 6 7 8]
[6 7 8]
[9]
[3 5 7]
[1 4 7]


In [67]:
np2 = np.array([[0,1,2,3,4,5], 
                [5,6,7,8,9,10],
               [11,12,13,14,15,16]])
print(np2[1,4])
print(np2[0:3,1:3])

9
[[ 1  2]
 [ 6  7]
 [12 13]]
