In [1]:
import numpy as np

a = np.array([2,5,1,7,0,18])

print(np.sort(a))

[ 0  1  2  5  7 18]


In [5]:
names = np.array(["Fishcher","Tal", "Capablanca","Anand","Kasparov"])
print(np.sort(names))

['Anand' 'Capablanca' 'Fishcher' 'Kasparov' 'Tal']


In [6]:
bools = np.array([True,False,True,True])
print(np.sort(bools))

[False  True  True  True]


In [7]:
threed = np.array([[[4,1,2],[7,9,1]],[[16,9,0],[8,9,1]]])
print(np.sort(threed))

[[[ 1  2  4]
  [ 1  7  9]]

 [[ 0  9 16]
  [ 1  8  9]]]


In [8]:
print(np.where(threed == 9))

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([1, 1, 1], dtype=int64))


In [14]:
op = np.where(threed % 2 == 0)
print(threed[op])

[ 4  2 16  0  8]


In [15]:
filtered = threed > 5
print(threed[filtered])

[ 7  9 16  9  8  9]
