In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [3]:
b = np.array([-3,-2,-4,19,10])

print(np.absolute(b))

[ 3  2  4 19 10]


In [4]:
print(np.exp(b))

[4.97870684e-02 1.35335283e-01 1.83156389e-02 1.78482301e+08
 2.20264658e+04]


In [5]:
print(min(b))
print(max(b))

-4
19


In [6]:
print(np.sign(b))

[-1 -1 -1  1  1]


In [10]:
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))
print(np.log(b))

[-0.14112001 -0.90929743  0.7568025   0.14987721 -0.54402111]
[-0.9899925  -0.41614684 -0.65364362  0.98870462 -0.83907153]
[ 0.14254654  2.18503986 -1.15782128  0.15158947  0.64836083]
[       nan        nan        nan 2.94443898 2.30258509]


C:\Users\Gowtham\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.


In [12]:
c = b.view()
print(c)
c[0] = -9
print(b)
print(c)

[-3 -2 -4 19 10]
[-9 -2 -4 19 10]
[-9 -2 -4 19 10]


In [14]:
d = b.copy()
print(d)
d[0] = -1
print(d)
print(b)

[-9 -2 -4 19 10]
[-1 -2 -4 19 10]
[-9 -2 -4 19 10]


In [26]:
e = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(e.shape)
reshape = e.reshape(2,6)
print(reshape)
print(reshape.shape)
threed = reshape.reshape(2,3,2)
print(threed)

(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
f = threed.reshape(-1)
print(f)
print(f.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
